#!/usr/bin/env node
import fs from "node:fs/promises";
import path from "node:path";

/*
 * miku-pptx2md runtime bundle
 * Version: 0.5.1
 */
export const version = "0.5.1";

const __mikuMsOfficeCore = (() => {
// Generated by miku-ms-office-core build:bundle.

// src/ts/binary-io.ts
var textEncoder = new TextEncoder();
var textDecoder = new TextDecoder();
function readUint16(data, offset) {
  return data[offset] | data[offset + 1] << 8;
}
function readUint32(data, offset) {
  return (data[offset] | data[offset + 1] << 8 | data[offset + 2] << 16 | data[offset + 3] << 24) >>> 0;
}
function writeUint16(buffer, offset, value) {
  buffer[offset] = value & 255;
  buffer[offset + 1] = value >>> 8 & 255;
}
function writeUint32(buffer, offset, value) {
  buffer[offset] = value & 255;
  buffer[offset + 1] = value >>> 8 & 255;
  buffer[offset + 2] = value >>> 16 & 255;
  buffer[offset + 3] = value >>> 24 & 255;
}
function concatBytes(parts) {
  const total = parts.reduce((sum, part) => sum + part.length, 0);
  const output = new Uint8Array(total);
  let offset = 0;
  for (const part of parts) {
    output.set(part, offset);
    offset += part.length;
  }
  return output;
}
function asBytes(data) {
  return typeof data === "string" ? textEncoder.encode(data) : data;
}

// src/ts/diagnostics.ts
function createDiagnostic(severity, code, message, path) {
  return path === void 0 ? { severity, code, message } : { severity, code, message, path };
}

// src/ts/opc-part-path.ts
function normalizeOpcPartPath(partPath) {
  const withoutHash = partPath.split("#", 1)[0] ?? "";
  const raw = withoutHash.replace(/\\/g, "/").replace(/^\/+/, "");
  const parts = [];
  for (const part of raw.split("/")) {
    if (part === "" || part === ".") {
      continue;
    }
    if (part === "..") {
      if (parts.length === 0) {
        throw new Error(`OPC part path escapes package root: ${partPath}`);
      }
      parts.pop();
      continue;
    }
    parts.push(part);
  }
  if (parts.length === 0) {
    throw new Error(`OPC part path is empty: ${partPath}`);
  }
  return parts.join("/");
}
function resolveOpcRelationshipTarget(sourcePartPath, target, targetMode = "") {
  if (targetMode.toLowerCase() === "external") {
    return target;
  }
  if (/^[a-z][a-z0-9+.-]*:/i.test(target)) {
    return target;
  }
  if (target.startsWith("/")) {
    return normalizeOpcPartPath(target);
  }
  const source = normalizeOpcPartPath(sourcePartPath);
  const sourceDirectory = source.includes("/") ? source.slice(0, source.lastIndexOf("/")) : "";
  return normalizeOpcPartPath(sourceDirectory === "" ? target : `${sourceDirectory}/${target}`);
}
function compareOpcPartPaths(a, b) {
  return a < b ? -1 : a > b ? 1 : 0;
}
function buildOpcRelationshipsPath(sourcePartPath) {
  const source = normalizeOpcPartPath(sourcePartPath);
  const slashIndex = source.lastIndexOf("/");
  const directory = slashIndex < 0 ? "" : source.slice(0, slashIndex);
  const fileName = slashIndex < 0 ? source : source.slice(slashIndex + 1);
  return directory === "" ? `_rels/${fileName}.rels` : `${directory}/_rels/${fileName}.rels`;
}

// src/ts/xml-helper.ts
function escapeXmlText(value) {
  return sanitizeXmlText(value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
function escapeXmlAttribute(value) {
  return escapeXmlText(value).replace(/"/g, "&quot;").replace(/'/g, "&apos;");
}
function sanitizeXmlText(value) {
  return value.replace(/[^\u0009\u000A\u000D\u0020-\uD7FF\uE000-\uFFFD]/g, "");
}
function parseXmlAttributes(tag) {
  const attributes = /* @__PURE__ */ new Map();
  const pattern = /([A-Za-z_][\w:.-]*)\s*=\s*(?:"([^"]*)"|'([^']*)')/g;
  for (const match of tag.matchAll(pattern)) {
    attributes.set(match[1], decodeXmlEntities(match[2] ?? match[3] ?? ""));
  }
  return attributes;
}
function decodeXmlEntities(value) {
  return value.replace(/&quot;/g, '"').replace(/&apos;/g, "'").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&amp;/g, "&");
}

// src/ts/opc-content-types.ts
function parseOpcContentTypesXml(xml) {
  const defaults = [];
  const overrides = [];
  for (const match of xml.matchAll(/<Default\b([^>]*)\/?>/g)) {
    const attributes = parseXmlAttributes(match[1] ?? "");
    const extension = attributes.get("Extension");
    const contentType = attributes.get("ContentType");
    if (extension !== void 0 && contentType !== void 0) {
      defaults.push({ extension, contentType });
    }
  }
  for (const match of xml.matchAll(/<Override\b([^>]*)\/?>/g)) {
    const attributes = parseXmlAttributes(match[1] ?? "");
    const partName = attributes.get("PartName");
    const contentType = attributes.get("ContentType");
    if (partName !== void 0 && contentType !== void 0) {
      overrides.push({ partName: normalizeOpcPartPath(partName), contentType });
    }
  }
  return { defaults, overrides };
}
function resolveOpcContentType(contentTypes, partPath) {
  const normalized = normalizeOpcPartPath(partPath);
  const override = contentTypes.overrides.find((item) => item.partName === normalized);
  if (override !== void 0) {
    return override.contentType;
  }
  const extension = normalized.includes(".") ? normalized.slice(normalized.lastIndexOf(".") + 1) : "";
  return contentTypes.defaults.find((item) => item.extension === extension)?.contentType;
}
function buildOpcContentTypesXml(contentTypes) {
  const defaults = contentTypes.defaults.map((item) => `<Default Extension="${escapeXmlAttribute(item.extension)}" ContentType="${escapeXmlAttribute(item.contentType)}"/>`).join("");
  const overrides = contentTypes.overrides.map((item) => `<Override PartName="/${escapeXmlAttribute(normalizeOpcPartPath(item.partName))}" ContentType="${escapeXmlAttribute(item.contentType)}"/>`).join("");
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">${defaults}${overrides}</Types>`;
}

// src/ts/opc-relationships.ts
function parseOpcRelationshipsXml(xml) {
  const relationships = [];
  const pattern = /<Relationship\b([^>]*)\/?>/g;
  for (const match of xml.matchAll(pattern)) {
    const attributes = parseXmlAttributes(match[1] ?? "");
    const id = attributes.get("Id");
    const type = attributes.get("Type");
    const target = attributes.get("Target");
    if (id === void 0 || type === void 0 || target === void 0) {
      continue;
    }
    const targetMode = attributes.get("TargetMode");
    relationships.push(
      targetMode === void 0 ? { id, type, target } : { id, type, target, targetMode }
    );
  }
  return relationships;
}
function buildOpcRelationshipsXml(relationships) {
  const rels = relationships.map((relationship) => {
    const targetMode = relationship.targetMode === void 0 ? "" : ` TargetMode="${escapeXmlAttribute(relationship.targetMode)}"`;
    return `<Relationship Id="${escapeXmlAttribute(relationship.id)}" Type="${escapeXmlAttribute(relationship.type)}" Target="${escapeXmlAttribute(relationship.target)}"${targetMode}/>`;
  }).join("");
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${rels}</Relationships>`;
}
function resolveOpcRelationships(relationships, sourcePartPath) {
  return relationships.map((relationship) => ({
    ...relationship,
    target: resolveOpcRelationshipTarget(sourcePartPath, relationship.target, relationship.targetMode)
  }));
}
function relationshipArrayToMap(relationships) {
  return new Map(relationships.map((relationship) => [relationship.id, relationship]));
}

// src/ts/crc32.ts
var crcTable = new Uint32Array(256);
for (let i = 0; i < 256; i += 1) {
  let c = i;
  for (let k = 0; k < 8; k += 1) {
    c = c & 1 ? 3988292384 ^ c >>> 1 : c >>> 1;
  }
  crcTable[i] = c >>> 0;
}
function crc32(data) {
  let crc = 4294967295;
  for (const value of data) {
    crc = crcTable[(crc ^ value) & 255] ^ crc >>> 8;
  }
  return (crc ^ 4294967295) >>> 0;
}

// src/ts/zip-package.ts
var EOCD_SIGNATURE = 101010256;
var CENTRAL_DIRECTORY_SIGNATURE = 33639248;
var LOCAL_FILE_SIGNATURE = 67324752;
var ZIP_GENERAL_PURPOSE_FLAG_UTF8 = 2048;
var FIXED_TIMESTAMP = new Date(Date.UTC(1980, 0, 1, 0, 0, 0));
function getDefaultZipEntryTimestamp() {
  return new Date(FIXED_TIMESTAMP.getTime());
}
function readZipPackage(data) {
  const diagnostics = [];
  const entries = [];
  const centralDirectory = readCentralDirectory(data, diagnostics);
  for (const central of centralDirectory) {
    try {
      const compressed = readZipEntryCompressedData(data, central);
      const entryData = central.method === 0 ? compressed : getNodeZlib().inflateRawSync(compressed);
      entries.push(buildZipEntry(central, entryData));
    } catch (error) {
      diagnostics.push(
        createDiagnostic(
          "error",
          "zip.entry.read_failed",
          error instanceof Error ? error.message : String(error),
          central.path
        )
      );
    }
  }
  return { entries, diagnostics };
}
async function readZipPackageAsync(data, options = {}) {
  const diagnostics = [];
  const entries = [];
  const centralDirectory = readCentralDirectory(data, diagnostics);
  for (const central of centralDirectory) {
    try {
      const compressed = readZipEntryCompressedData(data, central);
      const entryData = central.method === 0 ? compressed : await inflateZipRawAsync(compressed, central.uncompressedSize, central.path, options.inflateRaw);
      entries.push(buildZipEntry(central, entryData));
    } catch (error) {
      diagnostics.push(
        createDiagnostic(
          "error",
          "zip.entry.read_failed",
          error instanceof Error ? error.message : String(error),
          central.path
        )
      );
    }
  }
  return { entries, diagnostics };
}
function writeZipPackage(entries, options = {}) {
  const order = options.order ?? "stable";
  const prepared = prepareZipEntries(entries, options);
  if (order === "stable") {
    prepared.sort((a, b) => compareOpcPartPaths(a.path, b.path));
  }
  const localParts = [];
  const centralParts = [];
  let offset = 0;
  for (const entry of prepared) {
    const serialized = serializeZipEntry(entry, offset, options.compressionLevel);
    localParts.push(serialized.localHeader, serialized.compressed);
    centralParts.push(serialized.centralHeader);
    offset += serialized.localHeader.length + serialized.compressed.length;
  }
  const centralDirectory = concatBytes(centralParts);
  const end = buildEndOfCentralDirectory(prepared.length, centralDirectory.length, offset);
  return concatBytes([...localParts, centralDirectory, end]);
}
function getZipEntry(entries, entryPath) {
  const normalized = normalizeOpcPartPath(entryPath);
  return entries.find((entry) => entry.path === normalized);
}
function getZipTextEntry(entries, entryPath) {
  const entry = getZipEntry(entries, entryPath);
  return entry === void 0 ? void 0 : textDecoder.decode(entry.data);
}
function upsertZipEntry(entries, entry) {
  const normalized = normalizeOpcPartPath(entry.path);
  const next = entries.filter((item) => normalizeOpcPartPath(item.path) !== normalized);
  next.push({ ...entry, path: normalized });
  return next;
}
function prepareZipEntries(entries, options) {
  const timestamp = options.timestamp ?? FIXED_TIMESTAMP;
  const compression = options.compression ?? "store";
  return entries.map((entry) => ({
    path: normalizeOpcPartPath(entry.path),
    data: asBytes(entry.data),
    compression: entry.compression ?? compression,
    modifiedAt: entry.modifiedAt ?? timestamp
  }));
}
function serializeZipEntry(entry, localHeaderOffset, compressionLevel) {
  const nameBytes = textEncoder.encode(entry.path);
  const method = entry.compression === "store" ? 0 : 8;
  const compressed = compressZipEntryData(entry, compressionLevel);
  const crc = crc32(entry.data);
  const dosTime = toDosTime(entry.modifiedAt);
  const dosDate = toDosDate(entry.modifiedAt);
  return {
    localHeader: buildLocalFileHeader(entry, nameBytes, method, compressed.length, crc, dosTime, dosDate),
    centralHeader: buildCentralDirectoryHeader(
      entry,
      nameBytes,
      method,
      compressed.length,
      crc,
      dosTime,
      dosDate,
      localHeaderOffset
    ),
    compressed
  };
}
function compressZipEntryData(entry, compressionLevel) {
  return entry.compression === "store" ? entry.data : new Uint8Array(getNodeZlib().deflateRawSync(entry.data, { level: compressionLevel ?? 9 }));
}
function buildLocalFileHeader(entry, nameBytes, method, compressedSize, crc, dosTime, dosDate) {
  const localHeader = new Uint8Array(30 + nameBytes.length);
  writeUint32(localHeader, 0, LOCAL_FILE_SIGNATURE);
  writeUint16(localHeader, 4, 20);
  writeUint16(localHeader, 6, ZIP_GENERAL_PURPOSE_FLAG_UTF8);
  writeUint16(localHeader, 8, method);
  writeUint16(localHeader, 10, dosTime);
  writeUint16(localHeader, 12, dosDate);
  writeUint32(localHeader, 14, crc);
  writeUint32(localHeader, 18, compressedSize);
  writeUint32(localHeader, 22, entry.data.length);
  writeUint16(localHeader, 26, nameBytes.length);
  writeUint16(localHeader, 28, 0);
  localHeader.set(nameBytes, 30);
  return localHeader;
}
function buildCentralDirectoryHeader(entry, nameBytes, method, compressedSize, crc, dosTime, dosDate, localHeaderOffset) {
  const centralHeader = new Uint8Array(46 + nameBytes.length);
  writeUint32(centralHeader, 0, CENTRAL_DIRECTORY_SIGNATURE);
  writeUint16(centralHeader, 4, 20);
  writeUint16(centralHeader, 6, 20);
  writeUint16(centralHeader, 8, ZIP_GENERAL_PURPOSE_FLAG_UTF8);
  writeUint16(centralHeader, 10, method);
  writeUint16(centralHeader, 12, dosTime);
  writeUint16(centralHeader, 14, dosDate);
  writeUint32(centralHeader, 16, crc);
  writeUint32(centralHeader, 20, compressedSize);
  writeUint32(centralHeader, 24, entry.data.length);
  writeUint16(centralHeader, 28, nameBytes.length);
  writeUint16(centralHeader, 30, 0);
  writeUint16(centralHeader, 32, 0);
  writeUint16(centralHeader, 34, 0);
  writeUint16(centralHeader, 36, 0);
  writeUint32(centralHeader, 38, 0);
  writeUint32(centralHeader, 42, localHeaderOffset);
  centralHeader.set(nameBytes, 46);
  return centralHeader;
}
function buildEndOfCentralDirectory(entryCount, centralDirectorySize, centralDirectoryOffset) {
  const end = new Uint8Array(22);
  writeUint32(end, 0, EOCD_SIGNATURE);
  writeUint16(end, 4, 0);
  writeUint16(end, 6, 0);
  writeUint16(end, 8, entryCount);
  writeUint16(end, 10, entryCount);
  writeUint32(end, 12, centralDirectorySize);
  writeUint32(end, 16, centralDirectoryOffset);
  writeUint16(end, 20, 0);
  return end;
}
function readZipEntryCompressedData(data, central) {
  const localNameLength = readUint16(data, central.localHeaderOffset + 26);
  const localExtraLength = readUint16(data, central.localHeaderOffset + 28);
  const dataStart = central.localHeaderOffset + 30 + localNameLength + localExtraLength;
  return data.slice(dataStart, dataStart + central.compressedSize);
}
function buildZipEntry(central, entryData) {
  return {
    path: central.path,
    data: new Uint8Array(entryData),
    compression: central.method === 0 ? "store" : "deflate",
    compressedSize: central.compressedSize,
    uncompressedSize: central.uncompressedSize,
    crc32: central.crc,
    modifiedAt: central.modifiedAt
  };
}
function readCentralDirectory(data, diagnostics) {
  const eocdOffset = findEndOfCentralDirectory(data);
  if (eocdOffset < 0) {
    diagnostics.push(createDiagnostic("error", "zip.eocd.missing", "End of central directory was not found."));
    return [];
  }
  const entryCount = readUint16(data, eocdOffset + 10);
  const centralDirectoryOffset = readUint32(data, eocdOffset + 16);
  const entries = [];
  let offset = centralDirectoryOffset;
  for (let index = 0; index < entryCount; index += 1) {
    if (readUint32(data, offset) !== CENTRAL_DIRECTORY_SIGNATURE) {
      diagnostics.push(createDiagnostic("error", "zip.central_directory.invalid", "Central directory entry signature is invalid."));
      break;
    }
    const flags = readUint16(data, offset + 8);
    const method = readUint16(data, offset + 10);
    const time = readUint16(data, offset + 12);
    const date = readUint16(data, offset + 14);
    const crc = readUint32(data, offset + 16);
    const compressedSize = readUint32(data, offset + 20);
    const uncompressedSize = readUint32(data, offset + 24);
    const fileNameLength = readUint16(data, offset + 28);
    const extraLength = readUint16(data, offset + 30);
    const commentLength = readUint16(data, offset + 32);
    const localHeaderOffset = readUint32(data, offset + 42);
    const nameStart = offset + 46;
    const path = textDecoder.decode(data.slice(nameStart, nameStart + fileNameLength));
    if (method !== 0 && method !== 8) {
      diagnostics.push(createDiagnostic("error", "zip.compression.unsupported", `Unsupported ZIP compression method: ${method}`, path));
    } else {
      entries.push({
        path: normalizeOpcPartPath(path),
        method,
        flags,
        crc,
        compressedSize,
        uncompressedSize,
        localHeaderOffset,
        modifiedAt: fromDosDateTime(date, time)
      });
    }
    offset = nameStart + fileNameLength + extraLength + commentLength;
  }
  return entries;
}
function findEndOfCentralDirectory(data) {
  const minOffset = Math.max(0, data.length - 65535 - 22);
  for (let offset = data.length - 22; offset >= minOffset; offset -= 1) {
    if (readUint32(data, offset) === EOCD_SIGNATURE) {
      return offset;
    }
  }
  return -1;
}
function toDosTime(date) {
  return date.getUTCHours() << 11 | date.getUTCMinutes() << 5 | Math.floor(date.getUTCSeconds() / 2);
}
function toDosDate(date) {
  const year = Math.max(1980, date.getUTCFullYear());
  return year - 1980 << 9 | date.getUTCMonth() + 1 << 5 | date.getUTCDate();
}
function fromDosDateTime(date, time) {
  const year = 1980 + (date >>> 9 & 127);
  const month = date >>> 5 & 15;
  const day = date & 31;
  const hour = time >>> 11 & 31;
  const minute = time >>> 5 & 63;
  const second = (time & 31) * 2;
  return new Date(Date.UTC(year, month - 1, day, hour, minute, second));
}
async function inflateZipRawAsync(compressed, expectedSize, path, customInflateRaw) {
  const inflated = customInflateRaw === void 0 ? await defaultInflateZipRawAsync(compressed) : await customInflateRaw(compressed, expectedSize, path);
  const bytes = new Uint8Array(inflated);
  if (bytes.length !== expectedSize) {
    throw new Error(`Deflated ZIP entry size mismatch: ${path}`);
  }
  return bytes;
}
async function defaultInflateZipRawAsync(compressed) {
  const runtime = globalThis;
  if (typeof runtime.DecompressionStream === "function") {
    try {
      const stream = new Blob([compressed]).stream().pipeThrough(new runtime.DecompressionStream("deflate-raw"));
      const buffer = await new Response(stream).arrayBuffer();
      return new Uint8Array(buffer);
    } catch (_error) {
    }
  }
  return new Uint8Array(getNodeZlib().inflateRawSync(compressed));
}
function getNodeZlib() {
  const runtime = globalThis;
  const getBuiltinModule = runtime.process?.getBuiltinModule;
  const zlib = typeof getBuiltinModule === "function" ? getBuiltinModule("node:zlib") ?? getBuiltinModule("zlib") : void 0;
  if (zlib !== void 0 && typeof zlib.deflateRawSync === "function" && typeof zlib.inflateRawSync === "function") {
    return zlib;
  }
  throw new Error("Node zlib is required for synchronous ZIP deflate operations. Use stored entries, readZipPackageAsync with DecompressionStream, or inject an async inflater.");
}

// src/ts/office-package.ts
function readOfficePackage(data) {
  const zip = readZipPackage(data);
  return buildOfficePackageFromZipReadResult(zip.entries, zip.diagnostics);
}
async function readOfficePackageAsync(data, options = {}) {
  const zip = await readZipPackageAsync(data, options);
  return buildOfficePackageFromZipReadResult(zip.entries, zip.diagnostics);
}
function buildOfficePackageFromZipReadResult(entries, zipDiagnostics) {
  const diagnostics = [...zipDiagnostics];
  const contentTypesXml = getZipTextEntry(entries, "[Content_Types].xml");
  let contentTypes;
  if (contentTypesXml === void 0) {
    diagnostics.push(
      createDiagnostic(
        "warning",
        "opc.content_types.missing",
        "The package does not contain [Content_Types].xml.",
        "[Content_Types].xml"
      )
    );
  } else {
    contentTypes = parseOpcContentTypesXml(contentTypesXml);
  }
  return contentTypes === void 0 ? { entries, diagnostics } : { entries, contentTypes, diagnostics };
}
function listOfficeMediaParts(entries) {
  return entries.filter((entry) => normalizeOpcPartPath(entry.path).includes("/media/"));
}
function readOfficePartRelationships(entries, sourcePartPath, options = {}) {
  const relsXml = getZipTextEntry(entries, buildOpcRelationshipsPath(sourcePartPath));
  if (relsXml === void 0) {
    return [];
  }
  const relationships = parseOpcRelationshipsXml(relsXml);
  return options.resolveTargets === false ? relationships : resolveOpcRelationships(relationships, sourcePartPath);
}

return {
  readOfficePackage
};
})();
const { readOfficePackage } = __mikuMsOfficeCore;


const SUMMARY_FIELDS = [
    "slides",
    "slidesWithTitles",
    "textBlocks",
    "listItems",
    "tables",
    "hyperlinks",
    "imageAssets",
    "notesSlides",
    "comments",
    "warnings",
    "errors",
    "diagnostics"
];
function createPptx2MdSummaryJsonData(result) {
    return {
        version: 1,
        metadata: result.metadata,
        summary: result.summary,
        diagnostics: result.diagnostics,
        assets: result.assets.map(createAssetSummary)
    };
}
function createPptx2MdSummaryText(result) {
    const metadataLines = Object.entries(result.metadata)
        .map(([key, value]) => `metadata.${key}: ${value}`);
    const summaryLines = SUMMARY_FIELDS.map((field) => `${field}: ${result.summary[field]}`);
    return [
        ...metadataLines,
        ...(metadataLines.length > 0 ? [""] : []),
        ...summaryLines
    ].join("\n");
}
function createPptx2MdAssetsManifestData(assets) {
    return {
        version: 1,
        assets: assets.map((asset) => ({
            ...createAssetSummary(asset),
            documentPosition: {
                slideIndex: asset.slideIndex,
                blockIndex: asset.blockIndex,
                blockKind: asset.kind
            }
        }))
    };
}
function createAssetSummary(asset) {
    return {
        kind: asset.kind,
        sourcePath: asset.sourcePath,
        mediaType: asset.mediaType,
        altText: asset.altText,
        sourceTrace: asset.sourceTrace,
        slideIndex: asset.slideIndex,
        blockIndex: asset.blockIndex,
        relationshipId: asset.relationshipId,
        size: asset.bytes.byteLength
    };
}


function decodeXmlEntities(text) {
    return text
        .replace(/&lt;/g, "<")
        .replace(/&gt;/g, ">")
        .replace(/&quot;/g, "\"")
        .replace(/&apos;/g, "'")
        .replace(/&amp;/g, "&");
}
function stripXmlTags(text) {
    return text.replace(/<[^>]+>/g, "");
}
function collectTagBlocks(xml, localName) {
    const pattern = new RegExp(`<[^<\\s:]*:?${localName}\\b[\\s\\S]*?<\\/[^<\\s:]*:?${localName}>`, "g");
    return Array.from(xml.matchAll(pattern), (match) => match[0]);
}
function collectTextValues(xml) {
    const values = [];
    const pattern = /<[^<\s:]*:?t\b[^>]*>([\s\S]*?)<\/[^<\s:]*:?t>/g;
    for (const match of xml.matchAll(pattern)) {
        values.push(decodeXmlEntities(stripXmlTags(match[1])));
    }
    return values;
}
function getAttribute(tag, localName) {
    const pattern = new RegExp(`(?:^|\\s)(?:[^\\s:=]+:)?${localName}="([^"]*)"`);
    const match = tag.match(pattern);
    return match ? decodeXmlEntities(match[1]) : undefined;
}
function normalizePackagePath(baseDir, target) {
    const parts = `${baseDir}/${target}`.split("/");
    const normalized = [];
    for (const part of parts) {
        if (!part || part === ".") {
            continue;
        }
        if (part === "..") {
            normalized.pop();
            continue;
        }
        normalized.push(part);
    }
    return normalized.join("/");
}


function readZipEntries(bytes) {
    const officePackage = readOfficePackage(bytes);
    const errors = officePackage.diagnostics.filter((diagnostic) => diagnostic.severity === "error");
    if (errors.length > 0) {
        throw new Error(errors.map(formatOfficeDiagnostic).join("\n"));
    }
    const entries = new Map();
    for (const entry of officePackage.entries) {
        entries.set(entry.path, entry.data);
    }
    return entries;
}
function formatOfficeDiagnostic(diagnostic) {
    if (diagnostic.code === "zip.eocd.missing") {
        return "ZIP end of central directory was not found.";
    }
    return diagnostic.path ? `${diagnostic.path}: ${diagnostic.message}` : diagnostic.message;
}


function convertPptxToMarkdown(bytes, options = {}) {
    const entries = readZipEntries(bytes);
    const diagnostics = [];
    const metadata = parseCoreProperties(entries);
    const contentTypes = parseContentTypes(entries);
    const slides = parseSlides(entries, diagnostics, contentTypes);
    const assets = collectAssets(slides);
    const markdownTitle = options.title || metadata.title || options.fallbackTitle || "presentation";
    const markdown = renderMarkdown(markdownTitle, slides, diagnostics, options);
    const summary = createSummary(slides, assets, diagnostics);
    return {
        markdown,
        metadata,
        summary,
        diagnostics,
        assets
    };
}
function createSummary(slides, assets, diagnostics) {
    return {
        slides: slides.length,
        slidesWithTitles: slides.filter((slide) => Boolean(slide.title)).length,
        textBlocks: slides.reduce((sum, slide) => sum + countTextBlocks(slide), 0),
        listItems: slides.reduce((sum, slide) => sum + countListItems(slide), 0),
        tables: slides.reduce((sum, slide) => sum + countTables(slide), 0),
        hyperlinks: slides.reduce((sum, slide) => sum + countHyperlinks(slide), 0),
        imageAssets: assets.length,
        notesSlides: slides.filter((slide) => slide.notes.length > 0).length,
        comments: slides.reduce((sum, slide) => sum + slide.comments.length, 0),
        warnings: diagnostics.filter((diagnostic) => diagnostic.severity === "warning").length,
        errors: diagnostics.filter((diagnostic) => diagnostic.severity === "error").length,
        diagnostics: diagnostics.length
    };
}
function parseCoreProperties(entries) {
    const xml = readTextEntry(entries, "docProps/core.xml");
    if (!xml) {
        return {};
    }
    return removeEmptyMetadata({
        title: readElementText(xml, "title"),
        subject: readElementText(xml, "subject"),
        creator: readElementText(xml, "creator"),
        description: readElementText(xml, "description"),
        keywords: readElementText(xml, "keywords"),
        lastModifiedBy: readElementText(xml, "lastModifiedBy"),
        revision: readElementText(xml, "revision"),
        category: readElementText(xml, "category"),
        created: readElementText(xml, "created"),
        modified: readElementText(xml, "modified")
    });
}
function removeEmptyMetadata(metadata) {
    return Object.fromEntries(Object.entries(metadata).filter(([, value]) => typeof value === "string" && value.length > 0));
}
function readElementText(xml, localName) {
    const block = collectTagBlocks(xml, localName)[0];
    if (!block) {
        return undefined;
    }
    const value = decodeXmlEntities(stripXmlTags(block)).replace(/\s+/g, " ").trim();
    return value.length > 0 ? value : undefined;
}
function parseSlides(entries, diagnostics, contentTypes) {
    const presentationXml = readTextEntry(entries, "ppt/presentation.xml");
    const presentationRelsXml = readTextEntry(entries, "ppt/_rels/presentation.xml.rels");
    if (!presentationXml || !presentationRelsXml) {
        throw new Error("Required PPTX presentation parts were not found.");
    }
    const rels = parseRelationships(presentationRelsXml, "ppt");
    const slideIds = Array.from(presentationXml.matchAll(/<[^<\s:]*:?sldId\b[^>]*>/g))
        .map((match) => getRelationshipId(match[0]))
        .filter((value) => Boolean(value));
    return slideIds.map((relId, index) => {
        const slidePath = rels.get(relId);
        if (!slidePath) {
            diagnostics.push({
                severity: "warning",
                code: "missing-slide-relationship",
                message: `Slide relationship was not found: ${relId}`,
                source: "ppt/presentation.xml"
            });
            return { index: index + 1, path: "", blocks: [], notes: [], comments: [] };
        }
        const slideXml = readTextEntry(entries, slidePath);
        if (!slideXml) {
            diagnostics.push({
                severity: "warning",
                code: "missing-slide-part",
                message: `Slide part was not found: ${slidePath}`,
                source: slidePath
            });
            return { index: index + 1, path: slidePath, blocks: [], notes: [], comments: [] };
        }
        const slideRelationships = parseSlideRelationships(entries, slidePath);
        const comments = parseSlideComments(entries, slidePath, slideRelationships, diagnostics);
        const notes = parseSlideNotes(entries, slidePath, slideRelationships, diagnostics);
        return parseSlideXml(slideXml, slidePath, index + 1, notes, comments, slideRelationships, entries, contentTypes, diagnostics);
    });
}
function parseSlideComments(entries, slidePath, slideRelationships, diagnostics) {
    const slideRelsPath = buildRelationshipsPath(slidePath);
    const comments = [];
    const commentRels = slideRelationships.filter((relationship) => relationship.type.endsWith("/comments"));
    for (const rel of commentRels) {
        const commentsXml = readTextEntry(entries, rel.target);
        if (!commentsXml) {
            diagnostics.push({
                severity: "warning",
                code: "missing-comments-part",
                message: `Slide comments part was not found: ${rel.target}`,
                source: slideRelsPath
            });
            continue;
        }
        comments.push(...parseSlideCommentsXml(commentsXml, comments.length));
    }
    return comments;
}
function parseSlideCommentsXml(xml, offset) {
    return collectTagBlocks(xml, "cm")
        .map((commentXml, index) => {
        const commentTag = getFirstTag(commentXml, "cm");
        const authorId = commentTag ? getAttribute(commentTag, "authorId") : undefined;
        const date = commentTag ? getAttribute(commentTag, "dt") : undefined;
        return {
            label: `comment-${offset + index + 1}`,
            text: readElementText(commentXml, "text") || "",
            ...(authorId ? { authorId } : {}),
            ...(date ? { date } : {})
        };
    })
        .filter((comment) => comment.text.length > 0);
}
function getRelationshipId(tag) {
    const relMatch = tag.match(/\sr:(?:id|embed)="([^"]*)"/);
    if (relMatch) {
        return relMatch[1];
    }
    return undefined;
}
function parseRelationships(xml, baseDir) {
    const rels = new Map();
    for (const rel of parseRelationshipEntries(xml, baseDir)) {
        rels.set(rel.id, rel.target);
    }
    return rels;
}
function parseRelationshipEntries(xml, baseDir) {
    const rels = [];
    const pattern = /<[^<\s:]*:?Relationship\b[^>]*>/g;
    for (const match of xml.matchAll(pattern)) {
        const tag = match[0];
        const id = getAttribute(tag, "Id");
        const type = getAttribute(tag, "Type") || "";
        const target = getAttribute(tag, "Target");
        const targetMode = getAttribute(tag, "TargetMode");
        if (id && target) {
            rels.push({
                id,
                type,
                target: targetMode === "External" ? target : normalizePackagePath(baseDir, target),
                ...(targetMode ? { targetMode } : {})
            });
        }
    }
    return rels;
}
function parseSlideRelationships(entries, slidePath) {
    const slideRelsPath = buildRelationshipsPath(slidePath);
    const slideRelsXml = readTextEntry(entries, slideRelsPath);
    if (!slideRelsXml) {
        return [];
    }
    return parseRelationshipEntries(slideRelsXml, getPackageDir(slidePath));
}
function parseSlideNotes(entries, slidePath, slideRelationships, diagnostics) {
    const slideRelsPath = buildRelationshipsPath(slidePath);
    const notesRel = slideRelationships.find((rel) => rel.type.endsWith("/notesSlide"));
    if (!notesRel) {
        return [];
    }
    const notesXml = readTextEntry(entries, notesRel.target);
    if (!notesXml) {
        diagnostics.push({
            severity: "warning",
            code: "missing-notes-part",
            message: `Notes slide part was not found: ${notesRel.target}`,
            source: slideRelsPath
        });
        return [];
    }
    return parseNotesXml(notesXml);
}
function buildRelationshipsPath(partPath) {
    const dir = getPackageDir(partPath);
    const fileName = partPath.slice(dir.length ? dir.length + 1 : 0);
    return dir ? `${dir}/_rels/${fileName}.rels` : `_rels/${fileName}.rels`;
}
function getPackageDir(partPath) {
    const index = partPath.lastIndexOf("/");
    return index >= 0 ? partPath.slice(0, index) : "";
}
function parseNotesXml(xml) {
    return collectTagBlocks(xml, "sp")
        .filter((shapeXml) => !isNotesSlideImageShape(shapeXml))
        .flatMap((shapeXml) => extractShapeParagraphs(shapeXml));
}
function isNotesSlideImageShape(shapeXml) {
    const placeholderMatch = shapeXml.match(/<[^<\s:]*:?ph\b[^>]*>/);
    return placeholderMatch ? getAttribute(placeholderMatch[0], "type") === "sldImg" : false;
}
function parseSlideXml(xml, slidePath, index, notes, comments, slideRelationships, entries, contentTypes, diagnostics) {
    const elements = collectSlideContentElements(xml);
    const blocks = [];
    let title;
    for (const element of elements) {
        if (element.kind === "graphicFrame") {
            const table = parseGraphicFrameTable(element.xml);
            if (table) {
                if (table.diagnostic) {
                    diagnostics.push({
                        ...table.diagnostic,
                        source: slidePath
                    });
                }
                blocks.push(table);
            }
            else {
                diagnostics.push(createUnsupportedGraphicFrameDiagnostic(element.xml, slidePath));
            }
            continue;
        }
        if (element.kind === "pic") {
            const image = parsePictureImage(element.xml, slideRelationships, entries, contentTypes, slidePath, index, blocks.length, diagnostics);
            if (image) {
                blocks.push(image);
            }
            else {
                const unsupportedPicture = createUnsupportedPictureDiagnostic(element.xml, slidePath);
                if (unsupportedPicture) {
                    diagnostics.push(unsupportedPicture);
                }
            }
            continue;
        }
        const paragraphs = extractShapeParagraphs(element.xml, slideRelationships, diagnostics, slidePath);
        if (paragraphs.length === 0) {
            continue;
        }
        if (!title && isTitleShape(element.xml)) {
            title = paragraphs.map((paragraph) => paragraph.text).join(" ").trim();
            continue;
        }
        const shapeType = getOrdinaryShapeType(element.xml);
        if (shapeType) {
            blocks.push({
                kind: "shape-text",
                shapeType,
                paragraphs
            });
        }
        else {
            blocks.push(...paragraphs.map((paragraph) => ({
                kind: "paragraph",
                paragraph
            })));
        }
    }
    if (!title && blocks.length > 0) {
        title = undefined;
    }
    return {
        index,
        path: slidePath,
        title,
        blocks,
        notes,
        comments
    };
}
function collectSlideContentElements(xml) {
    const pattern = /<[^<\s:]*:?(sp|graphicFrame|pic)\b[\s\S]*?<\/[^<\s:]*:?\1>/g;
    return Array.from(xml.matchAll(pattern), (match) => ({
        kind: match[1],
        xml: match[0]
    }));
}
function extractShapeParagraphs(shapeXml, relationships = [], diagnostics, source) {
    const paragraphBlocks = collectTagBlocks(shapeXml, "p");
    return paragraphBlocks
        .map((paragraphXml) => parseTextParagraph(paragraphXml, relationships, diagnostics, source))
        .filter((paragraph) => paragraph.text.length > 0);
}
function parseTextParagraph(paragraphXml, relationships, diagnostics, source) {
    const runs = collectTextRuns(paragraphXml, relationships, diagnostics, source);
    const text = runs.map((run) => run.text).join("").replace(/\s+/g, " ").trim();
    const markdown = runs.map((run) => run.markdown).join("").replace(/\s+/g, " ").trim();
    const hyperlinkCount = runs.filter((run) => run.isHyperlink).length;
    const paragraphPropertiesTag = getFirstTag(paragraphXml, "pPr");
    const level = paragraphPropertiesTag ? parseListLevel(paragraphPropertiesTag) : 0;
    const listKind = detectListKind(paragraphXml);
    return {
        text,
        markdown,
        hyperlinkCount,
        level,
        ...(listKind ? { listKind } : {})
    };
}
function collectTextRuns(paragraphXml, relationships, diagnostics, source) {
    const runBlocks = collectTagBlocks(paragraphXml, "r");
    if (runBlocks.length === 0) {
        const text = collectTextValues(paragraphXml).join("");
        return [{ text, markdown: text, isHyperlink: false }];
    }
    return runBlocks.map((runXml) => {
        const text = collectTextValues(runXml).join("");
        const hyperlinkRelId = getHyperlinkRelationshipId(runXml);
        if (!hyperlinkRelId || text.length === 0) {
            return { text, markdown: applyInlineFormatting(text, runXml), isHyperlink: false };
        }
        const hyperlinkRel = relationships.find((rel) => rel.id === hyperlinkRelId && rel.type.endsWith("/hyperlink"));
        if (!hyperlinkRel) {
            diagnostics?.push({
                severity: "warning",
                code: "missing-hyperlink-relationship",
                message: `Hyperlink relationship was not found: ${hyperlinkRelId}`,
                ...(source ? { source } : {})
            });
            return { text, markdown: text, isHyperlink: false };
        }
        const linkLabel = applyInlineFormatting(escapeMarkdownLinkLabel(text), runXml);
        return {
            text,
            markdown: `[${linkLabel}](${escapeMarkdownLinkDestination(hyperlinkRel.target)})`,
            isHyperlink: true
        };
    });
}
function getHyperlinkRelationshipId(runXml) {
    const hyperlinkTag = getFirstTag(runXml, "hlinkClick");
    return hyperlinkTag ? getRelationshipId(hyperlinkTag) : undefined;
}
function applyInlineFormatting(text, runXml) {
    const runPropertiesTag = getFirstTag(runXml, "rPr");
    if (!runPropertiesTag) {
        return text;
    }
    const bold = getAttribute(runPropertiesTag, "b") === "1";
    const italic = getAttribute(runPropertiesTag, "i") === "1";
    const underline = isUnderlinedRun(runPropertiesTag);
    let formatted = text;
    if (bold && italic) {
        formatted = `***${formatted}***`;
    }
    else if (bold) {
        formatted = `**${formatted}**`;
    }
    else if (italic) {
        formatted = `*${formatted}*`;
    }
    if (underline) {
        return `<u>${formatted}</u>`;
    }
    return formatted;
}
function isUnderlinedRun(runPropertiesTag) {
    const underline = getAttribute(runPropertiesTag, "u");
    return underline !== undefined && underline !== "none";
}
function getFirstTag(xml, localName) {
    const pattern = new RegExp(`<[^<\\s:]*:?${localName}\\b[^>]*>`);
    return xml.match(pattern)?.[0];
}
function parseListLevel(paragraphPropertiesTag) {
    const rawLevel = getAttribute(paragraphPropertiesTag, "lvl");
    if (!rawLevel) {
        return 0;
    }
    const level = Number.parseInt(rawLevel, 10);
    if (!Number.isFinite(level) || level < 0) {
        return 0;
    }
    return Math.min(level, 8);
}
function detectListKind(paragraphXml) {
    if (/<[^<\s:]*:?buAutoNum\b[^>]*>/.test(paragraphXml)) {
        return "ordered";
    }
    if (/<[^<\s:]*:?buChar\b[^>]*>/.test(paragraphXml)) {
        return "bullet";
    }
    return undefined;
}
function parseGraphicFrameTable(graphicFrameXml) {
    const tableBlocks = collectTagBlocks(graphicFrameXml, "tbl");
    if (tableBlocks.length === 0) {
        return undefined;
    }
    const rows = collectTagBlocks(tableBlocks[0], "tr")
        .map((rowXml) => collectTagBlocks(rowXml, "tc")
        .map((cellXml) => collectTextValues(cellXml).join(" ").replace(/\s+/g, " ").trim()));
    if (rows.length === 0 || rows.every((row) => row.length === 0)) {
        return undefined;
    }
    return {
        kind: "table",
        rows,
        ...(hasMergedTableCells(tableBlocks[0]) ? {
            diagnostic: {
                severity: "warning",
                code: "limited-table-merged-cells",
                message: "PowerPoint table contains merged cells; Markdown table output is an approximate flattened representation."
            }
        } : {})
    };
}
function hasMergedTableCells(tableXml) {
    return /<[^<\s:]*:?tc\b[^>]*(?:gridSpan|rowSpan|hMerge|vMerge)="[^"]*"/.test(tableXml)
        || /<[^<\s:]*:?(?:hMerge|vMerge)\b/.test(tableXml);
}
function createUnsupportedGraphicFrameDiagnostic(graphicFrameXml, slidePath) {
    const kind = detectUnsupportedGraphicFrameKind(graphicFrameXml);
    return {
        severity: "warning",
        code: `unsupported-${kind}`,
        message: `Unsupported PowerPoint ${kind} graphic frame was omitted from Markdown output.`,
        source: slidePath
    };
}
function detectUnsupportedGraphicFrameKind(graphicFrameXml) {
    const graphicDataTag = getFirstTag(graphicFrameXml, "graphicData");
    const uri = graphicDataTag ? getAttribute(graphicDataTag, "uri") || "" : "";
    if (uri.includes("/chart")) {
        return "chart";
    }
    if (uri.includes("/diagram")) {
        return "smartart";
    }
    if (/<[^<\s:]*:?chart\b/.test(graphicFrameXml)) {
        return "chart";
    }
    if (/<[^<\s:]*:?relIds\b/.test(graphicFrameXml)) {
        return "smartart";
    }
    return "graphic-frame";
}
function parsePictureImage(pictureXml, slideRelationships, entries, contentTypes, slidePath, slideIndex, blockIndex, diagnostics) {
    const blipTag = getFirstTag(pictureXml, "blip");
    if (!blipTag) {
        return undefined;
    }
    const relId = getRelationshipId(blipTag);
    if (!relId) {
        return undefined;
    }
    const imageRel = slideRelationships.find((rel) => rel.id === relId && rel.type.endsWith("/image"));
    if (!imageRel) {
        diagnostics.push({
            severity: "warning",
            code: "missing-image-relationship",
            message: `Image relationship was not found: ${relId}`,
            source: slidePath
        });
        return undefined;
    }
    const bytes = entries.get(imageRel.target);
    if (!bytes) {
        diagnostics.push({
            severity: "warning",
            code: "missing-image-part",
            message: `Image part was not found: ${imageRel.target}`,
            source: slidePath
        });
        return undefined;
    }
    const nonVisualDrawingProps = getFirstTag(pictureXml, "cNvPr");
    const altText = nonVisualDrawingProps
        ? getAttribute(nonVisualDrawingProps, "descr") || getAttribute(nonVisualDrawingProps, "name") || imageRel.target
        : imageRel.target;
    return {
        kind: "image",
        asset: {
            kind: "image",
            sourcePath: imageRel.target,
            mediaType: getContentType(contentTypes, imageRel.target),
            altText,
            sourceTrace: `picture:image(${imageRel.target}):alt(${altText})`,
            slideIndex,
            blockIndex,
            relationshipId: relId,
            bytes
        }
    };
}
function createUnsupportedPictureDiagnostic(pictureXml, slidePath) {
    const kind = detectUnsupportedPictureKind(pictureXml);
    if (!kind) {
        return undefined;
    }
    return {
        severity: "warning",
        code: `unsupported-${kind}`,
        message: `Unsupported PowerPoint ${kind} picture object was omitted from Markdown output.`,
        source: slidePath
    };
}
function detectUnsupportedPictureKind(pictureXml) {
    if (/<[^<\s:]*:?videoFile\b/.test(pictureXml)) {
        return "video";
    }
    if (/<[^<\s:]*:?audioFile\b/.test(pictureXml)) {
        return "audio";
    }
    if (/<[^<\s:]*:?oleObj\b/.test(pictureXml)) {
        return "ole-object";
    }
    return undefined;
}
function parseContentTypes(entries) {
    const contentTypesXml = readTextEntry(entries, "[Content_Types].xml");
    const defaults = new Map();
    const overrides = new Map();
    if (!contentTypesXml) {
        return { defaults, overrides };
    }
    for (const match of contentTypesXml.matchAll(/<[^<\s:]*:?Default\b[^>]*>/g)) {
        const tag = match[0];
        const extension = getAttribute(tag, "Extension");
        const contentType = getAttribute(tag, "ContentType");
        if (extension && contentType) {
            defaults.set(extension.toLowerCase(), contentType);
        }
    }
    for (const match of contentTypesXml.matchAll(/<[^<\s:]*:?Override\b[^>]*>/g)) {
        const tag = match[0];
        const partName = getAttribute(tag, "PartName");
        const contentType = getAttribute(tag, "ContentType");
        if (partName && contentType) {
            overrides.set(partName.replace(/^\//, ""), contentType);
        }
    }
    return { defaults, overrides };
}
function getContentType(contentTypes, packagePath) {
    const override = contentTypes.overrides.get(packagePath);
    if (override) {
        return override;
    }
    const extension = packagePath.split(".").pop()?.toLowerCase() || "";
    return contentTypes.defaults.get(extension) || inferImageContentType(packagePath);
}
function inferImageContentType(packagePath) {
    const extension = packagePath.split(".").pop()?.toLowerCase();
    if (extension === "jpg" || extension === "jpeg") {
        return "image/jpeg";
    }
    if (extension === "gif") {
        return "image/gif";
    }
    if (extension === "webp") {
        return "image/webp";
    }
    if (extension === "svg") {
        return "image/svg+xml";
    }
    return "image/png";
}
function isTitleShape(shapeXml) {
    const placeholderMatch = shapeXml.match(/<[^<\s:]*:?ph\b[^>]*>/);
    if (!placeholderMatch) {
        return false;
    }
    const type = getAttribute(placeholderMatch[0], "type");
    return type === "title" || type === "ctrTitle";
}
function getOrdinaryShapeType(shapeXml) {
    if (hasPlaceholder(shapeXml) || isTextBoxShape(shapeXml)) {
        return undefined;
    }
    const presetGeometryMatch = shapeXml.match(/<[^<\s:]*:?prstGeom\b[^>]*>/);
    if (!presetGeometryMatch) {
        return undefined;
    }
    return getAttribute(presetGeometryMatch[0], "prst") || "shape";
}
function hasPlaceholder(shapeXml) {
    return /<[^<\s:]*:?ph\b[^>]*>/.test(shapeXml);
}
function isTextBoxShape(shapeXml) {
    const nonVisualShapePropsMatch = shapeXml.match(/<[^<\s:]*:?cNvSpPr\b[^>]*>/);
    return nonVisualShapePropsMatch ? getAttribute(nonVisualShapePropsMatch[0], "txBox") === "1" : false;
}
function countTextBlocks(slide) {
    return slide.blocks.reduce((sum, block) => {
        if (block.kind === "paragraph") {
            return sum + 1;
        }
        if (block.kind === "table") {
            return sum + block.rows.flat().filter((cell) => cell.length > 0).length;
        }
        if (block.kind === "image") {
            return sum;
        }
        return sum + block.paragraphs.length;
    }, slide.notes.length + slide.comments.length);
}
function collectAssets(slides) {
    return slides.flatMap((slide) => slide.blocks.flatMap((block) => block.kind === "image" ? [block.asset] : []));
}
function countListItems(slide) {
    const blockItems = slide.blocks.reduce((sum, block) => {
        if (block.kind === "paragraph") {
            return sum + (block.paragraph.listKind ? 1 : 0);
        }
        if (block.kind === "shape-text") {
            return sum + block.paragraphs.filter((paragraph) => paragraph.listKind).length;
        }
        return sum;
    }, 0);
    return blockItems + slide.notes.filter((paragraph) => paragraph.listKind).length;
}
function countTables(slide) {
    return slide.blocks.filter((block) => block.kind === "table").length;
}
function countHyperlinks(slide) {
    const blockLinks = slide.blocks.reduce((sum, block) => {
        if (block.kind === "paragraph") {
            return sum + block.paragraph.hyperlinkCount;
        }
        if (block.kind === "shape-text") {
            return sum + block.paragraphs.reduce((paragraphSum, paragraph) => paragraphSum + paragraph.hyperlinkCount, 0);
        }
        return sum;
    }, 0);
    return blockLinks + slide.notes.reduce((sum, paragraph) => sum + paragraph.hyperlinkCount, 0);
}
function renderMarkdown(title, slides, diagnostics, options = {}) {
    const lines = [`# ${escapeMarkdownText(title)}`, ""];
    for (const slide of slides) {
        const heading = slide.title
            ? `## Slide ${slide.index}: ${escapeMarkdownText(slide.title)}`
            : `## Slide ${slide.index}`;
        lines.push(heading, "");
        for (const block of slide.blocks) {
            if (block.kind === "shape-text") {
                lines.push(...renderShapeTextBlock(block), "");
            }
            else if (block.kind === "table") {
                lines.push(...renderTableBlock(block), "");
            }
            else if (block.kind === "image") {
                lines.push(renderImageBlock(block, options), "");
            }
            else {
                lines.push(renderParagraph(block.paragraph), "");
            }
        }
        if (options.includeNotes !== false && slide.notes.length > 0) {
            lines.push("### Speaker Notes", "");
            for (const note of slide.notes) {
                lines.push(renderParagraph(note), "");
            }
        }
        if (slide.comments.length > 0) {
            lines.push("### Comments", "");
            for (const comment of slide.comments) {
                lines.push(renderSlideComment(comment), "");
            }
        }
    }
    if (options.includeUnsupportedComments && diagnostics.length > 0) {
        lines.push("## Diagnostics", "");
        for (const diagnostic of diagnostics) {
            const source = diagnostic.source ? ` source=${diagnostic.source}` : "";
            lines.push(`<!-- ${diagnostic.severity}: ${diagnostic.code}${source}: ${diagnostic.message} -->`, "");
        }
    }
    const body = lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd();
    return shouldIncludeFrontMatter(options)
        ? `${createFrontMatter(title, options)}\n\n${body}\n`
        : `${body}\n`;
}
function shouldIncludeFrontMatter(options) {
    return String(options.frontMatter || "exclude") !== "exclude";
}
function createFrontMatter(title, options) {
    return [
        "---",
        `title: ${quoteYamlString(title)}`,
        "type: converted",
        "conversion:",
        "  tool: miku-pptx2md",
        `  version: ${quoteYamlString(String(options.toolVersion || "unknown"))}`,
        `  notes: ${options.includeNotes === false ? "exclude" : "include"}`,
        `  unsupported_comments: ${options.includeUnsupportedComments ? "include" : "exclude"}`,
        "---"
    ].join("\n");
}
function quoteYamlString(value) {
    return `"${String(value).replace(/\\/g, "\\\\").replace(/"/g, "\\\"").replace(/\r/g, "\\r").replace(/\n/g, "\\n")}"`;
}
function renderSlideComment(comment) {
    return `- [${escapeMarkdownText(comment.label)}] ${escapeMarkdownText(comment.text)}`;
}
function renderTableBlock(block) {
    const columnCount = Math.max(0, ...block.rows.map((row) => row.length));
    if (columnCount === 0) {
        return [];
    }
    const normalizedRows = block.rows.map((row) => normalizeTableRow(row, columnCount));
    const header = normalizedRows[0] || Array.from({ length: columnCount }, () => "");
    const bodyRows = normalizedRows.slice(1);
    const separator = Array.from({ length: columnCount }, () => "---");
    return [
        renderMarkdownTableRow(header),
        renderMarkdownTableRow(separator),
        ...bodyRows.map((row) => renderMarkdownTableRow(row))
    ];
}
function renderImageBlock(block, options) {
    const altText = escapeMarkdownText(block.asset.altText || "Image");
    const resolvedPath = options.imagePathResolver ? options.imagePathResolver(block.asset) : "";
    if (resolvedPath) {
        return `![${escapeMarkdownImageAlt(altText)}](${resolvedPath})`;
    }
    return `[Image: ${altText}]`;
}
function escapeMarkdownImageAlt(text) {
    return text.replace(/\]/g, "\\]");
}
function normalizeTableRow(row, columnCount) {
    return Array.from({ length: columnCount }, (_, index) => row[index] || "");
}
function renderMarkdownTableRow(row) {
    return `| ${row.map(escapeMarkdownTableCell).join(" | ")} |`;
}
function escapeMarkdownTableCell(text) {
    return escapeMarkdownText(text).replace(/\|/g, "\\|");
}
function renderShapeTextBlock(block) {
    return block.paragraphs.map((paragraph, index) => {
        const prefix = index === 0 ? `[Shape: ${block.shapeType}] ` : "";
        return `> ${prefix}${renderParagraph(paragraph)}`;
    });
}
function renderParagraph(paragraph) {
    const text = escapeMarkdownText(paragraph.markdown);
    if (!paragraph.listKind) {
        return text;
    }
    const indent = "  ".repeat(paragraph.level);
    const marker = paragraph.listKind === "ordered" ? "1." : "-";
    return `${indent}${marker} ${text}`;
}
function escapeMarkdownText(text) {
    return text.replace(/\r\n?/g, "\n");
}
function escapeMarkdownLinkLabel(text) {
    return escapeMarkdownText(text).replace(/([\\\[\]])/g, "\\$1");
}
function escapeMarkdownLinkDestination(text) {
    return text.replace(/\)/g, "%29").replace(/\s/g, "%20");
}
function readTextEntry(entries, path) {
    const data = entries.get(path);
    return data ? Buffer.from(data).toString("utf8") : undefined;
}


export { convertPptxToMarkdown, createPptx2MdSummaryText, createPptx2MdSummaryJsonData, createPptx2MdAssetsManifestData };

export default {
  version,
  convertPptxToMarkdown,
  createPptx2MdSummaryText,
  createPptx2MdSummaryJsonData,
  createPptx2MdAssetsManifestData
};


function getSafePptxPackagePathParts(packagePath) {
    if (!packagePath || packagePath.startsWith("/") || packagePath.includes("\\")) {
        throw new Error(`Unsafe PPTX asset path: ${packagePath}`);
    }
    const parts = packagePath.split("/");
    if (parts.some((part) => !part || part === "." || part === "..")) {
        throw new Error(`Unsafe PPTX asset path: ${packagePath}`);
    }
    return parts;
}




const FRONT_MATTER_MODES = new Set(["include", "exclude"]);

const FLAG_OPTIONS = {
  "--summary"(options) {
    options.summary = true;
  },
  "--no-notes"(options) {
    options.includeNotes = false;
  },
  "--debug"(options) {
    options.includeUnsupportedComments = true;
  },
  "--include-unsupported-comments"(options) {
    options.includeUnsupportedComments = true;
  },
  "--verbose"(options) {
    options.verbose = true;
  }
};

const VALUE_OPTIONS = {
  "--out": {
    apply(options, value) {
      options.outPath = value;
    }
  },
  "--assets-dir": {
    apply(options, value) {
      options.assetsDir = value;
    }
  },
  "--summary-out": {
    apply(options, value) {
      options.summaryOutPath = value;
    }
  },
  "--summary-json-out": {
    apply(options, value) {
      options.summaryJsonOutPath = value;
    }
  },
  "--front-matter": {
    apply(options, value) {
      if (!FRONT_MATTER_MODES.has(value)) {
        throw new Error(`Invalid front matter mode: ${value}`);
      }
      options.frontMatter = value;
    }
  }
};

function printHelp() {
  console.log(`miku-pptx2md - local-first PPTX to Markdown converter

USAGE
  node scripts/miku-pptx2md-cli.mjs <input.pptx> [options]
  node scripts/miku-pptx2md-cli.mjs --version
  node scripts/miku-pptx2md-cli.mjs --help

CONTRACT
  Input is exactly one local .pptx file path.
  Primary output is Markdown.
  If --out is set, Markdown is written to that file.
  If --out is omitted, Markdown is written to stdout.
  --summary prints conversion summary text to stdout.
  --summary-out writes conversion summary text to a file.
  --summary-json-out writes structured summary JSON to a file.
  If --out is omitted, avoid --summary unless mixed stdout output is acceptable.
  --verbose writes progress and timing diagnostics to stderr.
  --help and --version are metadata commands and must be used without other arguments.

OPTIONS
  --out <file>
      Write Markdown to this file. Parent directories are created.

  --assets-dir <dir>
      Export resolved embedded image assets into this directory.
      Also writes <dir>/manifest.json.
      Markdown image links are made relative to --out, or to the current directory
      when --out is omitted.

  --summary
      Print summary text to stdout.

  --summary-out <file>
      Write summary text to this file. Parent directories are created.

  --summary-json-out <file>
      Write structured summary JSON to this file. Parent directories are created.

  --front-matter <mode>
      include or exclude. Default: include.

  --no-notes
      Omit speaker notes from Markdown output.

  --debug
      Include diagnostic HTML comment traces in Markdown.

  --include-unsupported-comments
      Alias for --debug.

  --verbose
      Write progress and timing diagnostics to stderr with a "verbose:" prefix.
      Primary Markdown and summary outputs are unchanged.

  --version
      Show product name and package version, then exit.

  --help
      Show this help, then exit.

OUTPUTS
  Markdown:
      Main converted presentation structure. Starts with YAML front matter by
      default; use --front-matter exclude to omit it. Each slide is emitted as
      a section.

  Summary:
      Core metadata plus text, list, table, hyperlink, image, notes, and diagnostics counts.

  Asset directory:
      Contains resolved embedded image files at package-relative paths such as
      ppt/media/example.png, plus manifest.json.

  Asset manifest:
      JSON with asset path, media type, alt text, byte size, source trace,
      slide index, block index, relationship id, and document position.

EXAMPLES
  Write Markdown to a file:
    node scripts/miku-pptx2md-cli.mjs ./sample.pptx --out ./sample.md

  Print Markdown to stdout:
    node scripts/miku-pptx2md-cli.mjs ./sample.pptx

  Write Markdown and summary files:
    node scripts/miku-pptx2md-cli.mjs ./sample.pptx --out ./sample.md --summary-out ./sample.summary.txt

  Write structured summary JSON:
    node scripts/miku-pptx2md-cli.mjs ./sample.pptx --out ./sample.md --summary-json-out ./sample.summary.json

  Omit YAML front matter:
    node scripts/miku-pptx2md-cli.mjs ./sample.pptx --out ./sample.md --front-matter exclude

  Print a summary:
    node scripts/miku-pptx2md-cli.mjs ./sample.pptx --out ./sample.md --summary

  Write Markdown and export image assets:
    node scripts/miku-pptx2md-cli.mjs ./sample.pptx --out ./sample.md --assets-dir ./sample.assets

  Include diagnostic debug comments:
    node scripts/miku-pptx2md-cli.mjs ./sample.pptx --out ./sample.md --debug

  Show progress diagnostics on stderr:
    node scripts/miku-pptx2md-cli.mjs ./sample.pptx --out ./sample.md --verbose

  Show version:
    node scripts/miku-pptx2md-cli.mjs --version

EXIT CODES
  0  Success, or explicit metadata command such as --version / --help.
  1  CLI usage error, file I/O error, parse error, or unexpected runtime error.
`);
}

async function readPackageVersion() {
  return version;
}

function parseArgs(args) {
  if (args.length === 1 && args[0] === "--help") {
    return { help: true };
  }
  if (args.length === 1 && args[0] === "--version") {
    return { version: true };
  }
  if (args.includes("--help") || args.includes("--version")) {
    throw new Error("Use --help or --version without other arguments.");
  }

  const options = {
    inputPath: null,
    outPath: null,
    assetsDir: null,
    summaryOutPath: null,
    summaryJsonOutPath: null,
    summary: false,
    frontMatter: "include",
    includeNotes: true,
    includeUnsupportedComments: false,
    verbose: false
  };
  const positionals = [];

  for (let i = 0; i < args.length; i += 1) {
    const arg = args[i];
    if (!arg.startsWith("--")) {
      positionals.push(arg);
      continue;
    }

    const flagHandler = FLAG_OPTIONS[arg];
    if (flagHandler) {
      flagHandler(options);
      continue;
    }

    const valueOption = VALUE_OPTIONS[arg];
    if (valueOption) {
      const value = args[i + 1];
      if (!value) {
        throw new Error(`Missing value for ${arg}`);
      }
      i += 1;
      valueOption.apply(options, value);
      continue;
    }

    throw new Error(`Unknown option: ${arg}`);
  }

  if (positionals.length === 1) {
    [options.inputPath] = positionals;
  } else if (positionals.length > 1) {
    throw new Error("Specify exactly one input .pptx file.");
  }
  return options;
}

async function writeTextFile(outputPath, content) {
  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, content, "utf8");
}

function createVerboseLogger(enabled, startedAt) {
  return (message) => {
    if (!enabled) return;
    const elapsedMs = Date.now() - startedAt;
    console.error(`verbose: +${elapsedMs}ms ${message}`);
  };
}

function formatPresentationError(inputPath, stage, error) {
  const inputName = path.basename(inputPath || "input.pptx");
  const message = error instanceof Error ? error.message : String(error);
  return `[${inputName}] ${stage}: ${message}`;
}

function createSummaryJsonText(result) {
  return JSON.stringify(createPptx2MdSummaryJsonData(result), null, 2) + "\n";
}

async function writeBinaryFile(outputPath, content) {
  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, content);
}

function toPosixPath(filePath) {
  return filePath.split(path.sep).join("/");
}

function resolveAssetOutputPath(assetsRootDir, packagePath) {
  const outputPath = path.resolve(assetsRootDir, ...getSafePptxPackagePathParts(packagePath));
  const relativePath = path.relative(assetsRootDir, outputPath);
  if (relativePath.startsWith("..") || path.isAbsolute(relativePath)) {
    throw new Error(`PPTX asset path escapes assets directory: ${packagePath}`);
  }
  return outputPath;
}

function createAssetsManifestText(assets) {
  return JSON.stringify(createPptx2MdAssetsManifestData(assets), null, 2) + "\n";
}

async function readInputBytes(inputPath) {
  try {
    return await fs.readFile(inputPath);
  } catch (error) {
    throw new Error(formatPresentationError(inputPath, "read failed", error));
  }
}

function createImagePathResolver(resolvedAssetsDir, resolvedOutputPath) {
  if (!resolvedAssetsDir) {
    return undefined;
  }
  return (asset) => {
    const outputPath = resolveAssetOutputPath(resolvedAssetsDir, asset.sourcePath);
    const relativeBase = resolvedOutputPath ? path.dirname(resolvedOutputPath) : process.cwd();
    return toPosixPath(path.relative(relativeBase, outputPath) || path.basename(outputPath));
  };
}

function convertInputPresentation(inputBytes, options, resolvedAssetsDir, resolvedOutputPath, inputPath, packageVersion) {
  try {
    const inputStem = path.basename(options.inputPath).replace(/\.[^.]+$/, "");
    return convertPptxToMarkdown(inputBytes, {
      fallbackTitle: inputStem,
      frontMatter: options.frontMatter,
      toolVersion: packageVersion,
      includeNotes: options.includeNotes,
      includeUnsupportedComments: options.includeUnsupportedComments,
      imagePathResolver: createImagePathResolver(resolvedAssetsDir, resolvedOutputPath)
    });
  } catch (error) {
    throw new Error(formatPresentationError(inputPath, "parse failed", error));
  }
}

async function writeAssets(result, resolvedAssetsDir, inputPath) {
  if (!resolvedAssetsDir) {
    return;
  }

  try {
    await writeTextFile(path.join(resolvedAssetsDir, "manifest.json"), createAssetsManifestText(result.assets));
    for (const asset of result.assets) {
      await writeBinaryFile(resolveAssetOutputPath(resolvedAssetsDir, asset.sourcePath), asset.bytes);
    }
  } catch (error) {
    throw new Error(formatPresentationError(inputPath, "asset write failed", error));
  }
}

async function writeSummaryTextOutputs(result, options) {
  const summaryText = createPptx2MdSummaryText(result);

  if (options.summary) {
    console.log(summaryText);
  }
  if (options.summaryOutPath) {
    await writeTextFile(path.resolve(options.summaryOutPath), summaryText + "\n");
  }
}

async function writeSummaryJsonOutput(result, options) {
  if (options.summaryJsonOutPath) {
    await writeTextFile(path.resolve(options.summaryJsonOutPath), createSummaryJsonText(result));
  }
}

async function writeMarkdownOutput(result, resolvedOutputPath) {
  if (resolvedOutputPath) {
    await writeTextFile(resolvedOutputPath, result.markdown);
  } else {
    process.stdout.write(result.markdown);
  }
}

async function main() {
  const startedAt = Date.now();
  const options = parseArgs(process.argv.slice(2));
  const verbose = createVerboseLogger(options.verbose, startedAt);

  if (options.version) {
    const version = await readPackageVersion();
    console.log(`miku-pptx2md ${version}`);
    process.exit(0);
  }

  if (options.help || !options.inputPath) {
    printHelp();
    process.exit(options.help ? 0 : 1);
  }

  const inputPath = path.resolve(options.inputPath);
  const resolvedOutputPath = options.outPath ? path.resolve(options.outPath) : null;
  const resolvedAssetsDir = options.assetsDir ? path.resolve(options.assetsDir) : null;
  const packageVersion = await readPackageVersion();

  try {
    verbose(`input=${options.inputPath}`);
    verbose(`output=${options.outPath || "stdout"}`);
    verbose(`summary=${options.summaryOutPath || (options.summary ? "stdout" : "disabled")}`);
    verbose(`summary-json=${options.summaryJsonOutPath || "disabled"}`);
    verbose(`assets=${options.assetsDir || "disabled"}`);

    const inputBytes = await readInputBytes(inputPath);
    verbose(`input-bytes=${inputBytes.byteLength}`);

    const result = convertInputPresentation(inputBytes, options, resolvedAssetsDir, resolvedOutputPath, inputPath, packageVersion);
    verbose(`converted slides=${result.summary.slides} textBlocks=${result.summary.textBlocks} imageAssets=${result.summary.imageAssets}`);

    await writeAssets(result, resolvedAssetsDir, inputPath);
    if (resolvedAssetsDir) {
      verbose(`assets-written count=${result.assets.length}`);
    }

    try {
      await writeSummaryTextOutputs(result, options);
    } catch (error) {
      throw new Error(formatPresentationError(inputPath, "summary write failed", error));
    }
    if (options.summary) {
      verbose("summary-written stdout");
    }
    if (options.summaryOutPath) {
      verbose(`summary-written ${options.summaryOutPath}`);
    }

    try {
      await writeSummaryJsonOutput(result, options);
    } catch (error) {
      throw new Error(formatPresentationError(inputPath, "summary JSON write failed", error));
    }
    if (options.summaryJsonOutPath) {
      verbose(`summary-json-written ${options.summaryJsonOutPath}`);
    }

    try {
      await writeMarkdownOutput(result, resolvedOutputPath);
    } catch (error) {
      throw new Error(formatPresentationError(inputPath, "markdown write failed", error));
    }
    if (resolvedOutputPath) {
      verbose(`markdown-written ${options.outPath}`);
    } else {
      verbose("markdown-written stdout");
    }
    verbose(`done total-ms=${Date.now() - startedAt}`);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    if (message.startsWith(`[${path.basename(inputPath)}] `)) {
      throw error;
    }
    throw new Error(formatPresentationError(inputPath, "failed", error));
  }
}

main().catch((error) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error(message);
  process.exit(1);
});

